name: develop 브랜치 배포 자동화

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle 명령 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 종속성 캐싱
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle bootJar
        run: ./gradlew bootJar

      - name: GitHub Container Registry 로그인
        run: |
          export CR_PAT=${{ secrets.SIGNAL_BUDDY_TOKEN }}
          echo CR_PAT | docker login ghcr.io -u ${{ secrets.GIT_ID }} --password-stdin

      - name: 도커 이미지 생성
        run: |
          TAG=$(git rev-parse --short HEAD)
          DOCKER_IMAGE=${{ secrets.DOCKER_REGISTRY }}/signal-buddy:$TAG
          docker build -t test -f submodule/docker/Dockerfile .
          docker tag test $DOCKER_IMAGE
          docker push $DOCKER_IMAGE

      - name: Jenkins Webhook 호출
        run: |
          curl -X POST ${{ secrets.JENKINS_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Hookshot/56ca054" \
            -d '{"ref": "refs/heads/develop"}'